# Generated by Django 5.1 on 2025-04-12 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=255, verbose_name='Ответ')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faq.faq', verbose_name='Место')),
            ],
        ),
        migrations.DeleteModel(
            name='FAQItems',
        ),
    ]
