# Generated by Django 5.1 on 2025-04-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faqitem_delete_faqitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Место'),
        ),
    ]
