# Generated by Django 5.1 on 2025-04-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_faq_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='answer_en',
            field=models.TextField(max_length=255, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_ky',
            field=models.TextField(max_length=255, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_en',
            field=models.TextField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_ky',
            field=models.TextField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
    ]
