# Generated by Django 5.1 on 2025-03-17 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('icon', models.FileField(upload_to='partners_icons/%Y/%m/', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Под заголовок')),
                ('subtitle_ru', models.CharField(max_length=255, null=True, verbose_name='Под заголовок')),
                ('subtitle_en', models.CharField(max_length=255, null=True, verbose_name='Под заголовок')),
                ('subtitle_ky', models.CharField(max_length=255, null=True, verbose_name='Под заголовок')),
                ('photo', models.FileField(upload_to='partner_documents/photos/%Y/%m/', verbose_name='Фото')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыт?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Коллекция документов',
                'verbose_name_plural': 'Коллекции документов',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PartnerDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('document', models.FileField(upload_to='partners_documents/files/%Y/%m/', verbose_name='Файл')),
                ('document_ru', models.FileField(null=True, upload_to='partners_documents/files/%Y/%m/', verbose_name='Файл')),
                ('document_en', models.FileField(null=True, upload_to='partners_documents/files/%Y/%m/', verbose_name='Файл')),
                ('document_ky', models.FileField(null=True, upload_to='partners_documents/files/%Y/%m/', verbose_name='Файл')),
                ('partner_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_items', to='partners.partnerdocument')),
            ],
            options={
                'verbose_name': 'Элемент коллекции Документа',
                'verbose_name_plural': 'Элементы коллекции Документа',
            },
        ),
    ]
