# Generated by Django 5.1 on 2025-03-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт?'),
        ),
    ]
