# Generated by Django 5.1 on 2025-03-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на партнера'),
        ),
    ]
