# Generated by Django 5.1 on 2025-03-04 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название коллекции')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название коллекции')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название коллекции')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция документов',
                'verbose_name_plural': 'Коллекции документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название файла')),
                ('document', models.FileField(upload_to='document_pages/files/%Y/%m/', verbose_name='Файл')),
                ('document_ru', models.FileField(null=True, upload_to='document_pages/files/%Y/%m/', verbose_name='Файл')),
                ('document_en', models.FileField(null=True, upload_to='document_pages/files/%Y/%m/', verbose_name='Файл')),
                ('document_ky', models.FileField(null=True, upload_to='document_pages/files/%Y/%m/', verbose_name='Файл')),
                ('document_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_collection_items', to='document_pages.documentcollection')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('subtitle', models.CharField(max_length=255, verbose_name='Под заголовок')),
                ('subtitle_ru', models.CharField(max_length=255, null=True, verbose_name='Под заголовок')),
                ('subtitle_en', models.CharField(max_length=255, null=True, verbose_name='Под заголовок')),
                ('subtitle_ky', models.CharField(max_length=255, null=True, verbose_name='Под заголовок')),
                ('photo', models.FileField(upload_to='document_pages/photos/%Y/%m/', verbose_name='Фото')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('content_en', models.TextField(null=True, verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('document_collections', models.ManyToManyField(to='document_pages.documentcollection', verbose_name='Коллекции документов')),
            ],
            options={
                'verbose_name': 'Страница документов',
                'verbose_name_plural': 'Страницы документов',
            },
        ),
    ]
