# Generated by Django 5.1 on 2025-03-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
