# Generated by Django 5.1 on 2025-03-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0002_documentpage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentpage',
            options={'ordering': ('order',), 'verbose_name': 'Страница документов', 'verbose_name_plural': 'Страницы документов'},
        ),
    ]
