# Generated by Django 5.1 on 2025-03-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0004_documentpage_parent_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='document_collections',
            field=models.ManyToManyField(blank=True, to='document_pages.documentcollection', verbose_name='Коллекции документов'),
        ),
    ]
