# Generated by Django 5.1 on 2025-03-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0005_alter_documentpage_document_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpage',
            name='document_collections',
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='document_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='document_pages.documentpage', verbose_name='Страница документов'),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок на странице'),
        ),
    ]
