# Generated by Django 5.1 on 2025-03-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0006_remove_documentpage_document_collections_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcollection',
            options={'ordering': ('order',), 'verbose_name': 'Коллекция документов', 'verbose_name_plural': 'Коллекции документов'},
        ),
    ]
