# Generated by Django 5.1 on 2025-03-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0007_alter_documentcollection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcollection',
            options={'verbose_name': 'Коллекция документов', 'verbose_name_plural': 'Коллекции документов'},
        ),
        migrations.RemoveField(
            model_name='documentcollection',
            name='document_page',
        ),
        migrations.RemoveField(
            model_name='documentcollection',
            name='order',
        ),
        migrations.AddField(
            model_name='documentpage',
            name='document_collections',
            field=models.ManyToManyField(blank=True, to='document_pages.documentcollection', verbose_name='Коллекции документов'),
        ),
    ]
