# Generated by Django 5.1 on 2025-04-16 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0008_alter_documentcollection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcollectionitem',
            name='document_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_collection_items', to='document_pages.documentcollection'),
        ),
    ]
