# Generated by Django 5.1 on 2025-04-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0009_alter_documentcollectionitem_document_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcollection',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='collections', to='document_pages.documentcollectionitem', verbose_name='Документы'),
        ),
    ]
