# Generated by Django 5.1 on 2025-02-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название направления')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/photos/%Y/%m/%d/', verbose_name='Фото студента')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО студента')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления записи')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано или нет')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.category', verbose_name='Направление')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.question_answer', verbose_name='Вопрос-Ответ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.student', verbose_name='Студент')),
            ],
        ),
    ]
