# Generated by Django 5.1 on 2025-04-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название направления')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='reviews/photos/%Y/%m/%d/', verbose_name='Фото студента')),
                ('student_full_name', models.CharField(max_length=100, verbose_name='ФИО студента')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('student_course', models.IntegerField(verbose_name='Курс')),
                ('student_status', models.CharField(choices=[('student', 'Студент'), ('graduate', 'Выпускник')], default='student', max_length=10, verbose_name='Статус студента или выпускника')),
                ('question_answer', models.ManyToManyField(blank=True, to='reviews.questionanswer', verbose_name='Вопросы и ответы')),
                ('student_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.category', verbose_name='Направление')),
            ],
        ),
    ]
