# Generated by Django 5.1 on 2025-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название направления'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Название направления'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название направления'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer_ky',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_en',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_ky',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО студента'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_full_name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО студента'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО студента'),
        ),
    ]
