# Generated by Django 5.1 on 2025-02-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='question_answer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cat',
        ),
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='reviews/photos/%Y/%m/%d/', verbose_name='Фото студента')),
                ('student_full_name', models.CharField(max_length=100, verbose_name='ФИО студента')),
                ('student_course', models.IntegerField(verbose_name='Курс')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления записи')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано или нет')),
                ('student_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.category', verbose_name='Направление')),
            ],
        ),
        migrations.DeleteModel(
            name='Question_Answer',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
