# Generated by Django 5.1 on 2025-02-25 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_question_answer_remove_review_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreview',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='studentreview',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentreview',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='studentreview',
            name='time_update',
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('student_review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_answers', to='reviews.studentreview', verbose_name='Студент')),
            ],
        ),
    ]
