# Generated by Django 5.1 on 2025-03-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_studentreview_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreview',
            old_name='student_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='studentreview',
            old_name='student_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentreview',
            old_name='student_full_name',
            new_name='full_name',
        ),
    ]
