# Generated by Django 5.1 on 2025-03-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_studentreview_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название направления'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Название направления'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название направления'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.category', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_category_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.category', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.category', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_course_en',
            field=models.IntegerField(null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_course_ky',
            field=models.IntegerField(null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_course_ru',
            field=models.IntegerField(null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО студента'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_full_name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО студента'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО студента'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_status',
            field=models.CharField(choices=[('student', 'Студент'), ('graduate', 'Выпускник')], default='student', max_length=10, verbose_name='Статус студента или выпускника'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_status_en',
            field=models.CharField(choices=[('student', 'Студент'), ('graduate', 'Выпускник')], default='student', max_length=10, null=True, verbose_name='Статус студента или выпускника'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_status_ky',
            field=models.CharField(choices=[('student', 'Студент'), ('graduate', 'Выпускник')], default='student', max_length=10, null=True, verbose_name='Статус студента или выпускника'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_status_ru',
            field=models.CharField(choices=[('student', 'Студент'), ('graduate', 'Выпускник')], default='student', max_length=10, null=True, verbose_name='Статус студента или выпускника'),
        ),
    ]
