# Generated by Django 5.1 on 2025-03-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_student_category_studentreview_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreview',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/photos/%Y/%m', verbose_name='Фото студента'),
        ),
    ]
