# Generated by Django 5.1 on 2025-04-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='room_number_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_number_ky',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_number_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name_ky',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='week_type_en',
            field=models.CharField(choices=[('Числитель', 'Числитель'), ('Знаменатель', 'Знаменатель')], default='Числитель', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='week_type_ky',
            field=models.CharField(choices=[('Числитель', 'Числитель'), ('Знаменатель', 'Знаменатель')], default='Числитель', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='week_type_ru',
            field=models.CharField(choices=[('Числитель', 'Числитель'), ('Знаменатель', 'Знаменатель')], default='Числитель', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='lesson_type_en',
            field=models.CharField(default='Лекция', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='lesson_type_ky',
            field=models.CharField(default='Лекция', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='lesson_type_ru',
            field=models.CharField(default='Лекция', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='technology_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='technology_ky',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='technology_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='title_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
