# Generated by Django 5.1 on 2025-02-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default=1, max_length=255, verbose_name='Место проведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='place_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Место проведения'),
        ),
    ]
