# Generated by Django 5.1 on 2025-04-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parliamentmember',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='parliamentmember',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='parliamentmember',
            name='description_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='parliamentmember',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
