# Generated by Django 5.1 on 2025-02-01 18:49

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='specialty/photos/%Y/%m', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('specialty', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preview_photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='specialty/preview_photos/%Y/%m', verbose_name='Фото')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='specialty/photos/%Y/%m', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.specialtycategory')),
            ],
        ),
    ]
