# Generated by Django 5.1 on 2025-02-04 07:40

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='preview_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='specialty/preview_photos/%Y/%m', verbose_name='Превью Фото'),
        ),
    ]
