# Generated by Django 5.1 on 2025-02-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0004_alter_course_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='photo',
            field=models.FileField(blank=True, upload_to='specialty/photos/%Y/%m', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='preview_photo',
            field=models.FileField(blank=True, upload_to='specialty/preview_photos/%Y/%m', verbose_name='Превью Фото'),
        ),
    ]
