# Generated by Django 5.1 on 2025-02-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0005_alter_specialty_photo_alter_specialty_preview_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtycategory',
            name='photo',
            field=models.FileField(blank=True, upload_to='specialty/photos/%Y/%m', verbose_name='Фото'),
        ),
    ]
