# Generated by Django 5.1 on 2025-02-12 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0006_alter_specialtycategory_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty', to='specialties.specialtycategory'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='specialties.specialty', verbose_name='Специальность'),
        ),
    ]
