# Generated by Django 5.1 on 2025-02-12 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0007_alter_specialty_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('photo', models.FileField(upload_to='specialty/student_projects/%Y/%m/', verbose_name='Фото проекта')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to='specialties.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Проект студентов',
                'verbose_name_plural': 'Проекты студентов',
            },
        ),
    ]
