# Generated by Django 5.1 on 2025-02-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0008_studentproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название инструмента')),
                ('photo', models.FileField(upload_to='specialty/cv/tools/%Y/%m', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('photo', models.ImageField(upload_to='specialty/cv/%Y/%m', verbose_name='Аватар')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='specialties.specialty', verbose_name='Специальность')),
                ('skills', models.ManyToManyField(blank=True, null=True, to='specialties.skill', verbose_name='Навыки')),
                ('tools', models.ManyToManyField(blank=True, null=True, to='specialties.tool', verbose_name='Инструменты')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
