# Generated by Django 5.1 on 2025-02-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0010_remove_cv_specialty_remove_studentproject_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='cv',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='cv',
            name='position_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='cv',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название навыка'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название навыка'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название навыка'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialtycategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialtycategory',
            name='name_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialtycategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='tool',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название инструмента'),
        ),
        migrations.AddField(
            model_name='tool',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название инструмента'),
        ),
        migrations.AddField(
            model_name='tool',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название инструмента'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='portfolio_projects_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Количество работ'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='portfolio_projects_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Количество работ'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='portfolio_projects_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Количество работ'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='training_time_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Время обучения'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='training_time_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Время обучения'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='training_time_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Время обучения'),
        ),
    ]
