# Generated by Django 5.1 on 2025-03-05 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0012_alter_specialty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_program', to='specialties.specialty'),
        ),
    ]
