# Generated by Django 5.1 on 2025-03-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0014_alter_trainingprogram_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='specialty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_program', to='specialties.specialty'),
        ),
    ]
