# Generated by Django 5.1 on 2025-03-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0015_alter_trainingprogram_specialty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('order',), 'verbose_name': 'Курс - Программа обучения', 'verbose_name_plural': 'Курс - Программы обучения'},
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
