# Generated by Django 5.1 on 2025-04-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0017_alter_course_options_remove_course_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярное'),
        ),
    ]
