# Generated by Django 5.1 on 2025-03-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('text_en', models.TextField(null=True, verbose_name='Текст')),
                ('text_ky', models.TextField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Страницы абитуриентам',
                'verbose_name_plural': 'Страница абитуриентам',
            },
        ),
    ]
